services:
  tests:
    build: .
    shm_size: '2gb'
    environment:
      - BASE_URL=${BASE_URL}
      - TEST_USER=${TEST_USER}
      - TEST_PASS=${TEST_PASS}
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results