name: Playwright Tests with Allure & Email

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Ditambahkan agar bisa menerima sinyal trigger dari repo aplikasi demo
  repository_dispatch:
    types: [run-automation]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      run: npx playwright test
      continue-on-error: true
      
    - name: Install Allure Commandline
      if: always()
      run: npm install -g allure-commandline --save-dev

    - name: Generate Allure Report
      if: always()
      run: |
        allure generate allure-results --clean -o allure-report

    # Langkah untuk mengunggah halaman Allure ke GitHub Pages
    - name: Upload page artifact
      uses: actions/upload-pages-artifact@v3
      if: always()
      with:
        path: allure-report

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      if: always()

    - name: Upload Playwright/Allure Artifacts
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-reports
        path: |
          playwright-report/
          allure-report/
        retention-days: 30

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      if: always()
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "CI/CD Test Report - Status: ${{ job.status }}"
        to: ilman.arif29@gmail.com
        from: Automation CI/CD <no-reply@github.com>
        body: |
          Halo,
          
          Pengujian otomatisasi regresi (Playwright) telah selesai dijalankan di server.
          Status Pipeline: ${{ job.status }}
          
          Anda dapat melihat laporan lengkap Allure secara interaktif melalui tautan berikut:
          👉 https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
          
          Silakan cek repositori GitHub untuk mengunduh artifact laporan lengkap jika diperlukan.